//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryShengals
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryShengalsEntities : DbContext
    {
        public LibraryShengalsEntities()
            : base("name=LibraryShengalsEntities")
        {
        }

        private static LibraryShengalsEntities _context;
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static LibraryShengalsEntities GetContext()
        {
            if (_context == null)
            {
                _context = new LibraryShengalsEntities();
            }
            return _context;
        }

        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
